In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
import warnings
warnings.filterwarnings("ignore")
import os
os.getcwd()

'C:\\Users\\mrabh\\Documents'

In [8]:
df=pd.read_excel(r"D:\\Data Set ML\\Churn_Modelling.xlsx")

In [9]:
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [10]:
df.shape

(10000, 14)

**Preprocessing The Dataset**
* Part1 - HAndling Missing Value

In [11]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# Part-2 Encoding Concept
1. Label Encoder - Char To Number
2. One Hot encoder - Converts different Column By using Binary Value
3. Dummy Variable - (n-1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [13]:
df=df.iloc[:,3:]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [15]:
df["Geography"]=df["Geography"].astype("category")
df["Geography"]=df["Geography"].cat.codes

In [16]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [17]:
df=pd.get_dummies(df, columns=["Geography"])

In [18]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619  Female   42       2       0.00              1          1   
1          608  Female   41       1   83807.86              1          0   
2          502  Female   42       8  159660.80              3          1   
3          699  Female   39       1       0.00              2          0   
4          850  Female   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_0  Geography_1  \
0               1        101348.88       1            1            0   
1               1        112542.58       0            0            0   
2               0        113931.57       1            1            0   
3               0         93826.63       0            1            0   
4               1         79084.10       0            0            0   

   Geography_2  
0            0  
1            1  
2            0  
3            0  
4            1

In [19]:
# Dummy Variables
df=df.drop(["Geography_0"],axis=1)

In [20]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619  Female   42       2       0.00              1          1   
1          608  Female   41       1   83807.86              1          0   
2          502  Female   42       8  159660.80              3          1   
3          699  Female   39       1       0.00              2          0   
4          850  Female   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_1  Geography_2  
0               1        101348.88       1            0            0  
1               1        112542.58       0            0            1  
2               0        113931.57       1            0            0  
3               0         93826.63       0            0            0  
4               1         79084.10       0            0            1

In [21]:
df["Gender"]=df["Gender"].astype("category")
df["Gender"]=df["Gender"].cat.codes
df=pd.get_dummies(df, columns=["Gender"])

In [28]:
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_1  Geography_2  Gender_1  
0               1        101348.88       1            0            0         0  
1               1        112542.58       0            0            1         0  
2               0        113931.57       1            0            0         0  
3               0         93826.63       0            0            0         0  
4               1         79084.10       0            0            1         0

In [29]:
df=df.drop(["Gender_0"],axis=1)

In [31]:
x=df.drop(["Exited"],axis=1)
y=df["Exited"]

# Preprocessing Part-3 
1. Outlier
# Preprocessing Part - 4
1. Standardisation

In [34]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57873591,
        -0.57380915, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57873591,
        -0.57380915, -1.09598752]])

In [32]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  Gender_1  
0               1        101348.88            0            0         0  
1               1        112542.58            0            1         0  
2               0        113931.57            0            0         0  
3               0         93826.63            0            0         0  
4               1         79084.10            0            1         0

In [33]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [37]:
x=pd.DataFrame(x)
x.head(3)

0         1         2         3         4         5         6   \
0 -0.326221  0.293517 -1.041760 -1.225848 -0.911583  0.646092  0.970243   
1 -0.440036  0.198164 -1.387538  0.117350 -0.911583 -1.547768  0.970243   
2 -1.536794  0.293517  1.032908  1.333053  2.527057  0.646092 -1.030670   

         7         8         9         10  
0  0.021886 -0.578736 -0.573809 -1.095988  
1  0.216534 -0.578736  1.742740 -1.095988  
2  0.240687 -0.578736 -0.573809 -1.095988

**This is Applicable For ClassiFication problem** 
# Pre- Processing Part 5: Imbalance Dataset

In [38]:
y.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

#### The data Is Imbalance Hence We have To use either Oversampling or Smote

In [40]:
import imblearn

In [41]:
from imblearn.over_sampling import RandomOverSampler
over=RandomOverSampler()
x_over, y_over= over.fit_resample(x,y)

In [42]:
print(x_over.shape)
print(y_over.shape)

(15926, 11)
(15926,)


#### This Is All about Preprocessing Method
## Now we Are Ready To split The data Into Training and Test for BUilding model and Prediction

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_over,y_over, test_size=0.25,random_state=101)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(11944, 11)
(3982, 11)
(11944,)
(3982,)


# Building Model
1.Bagging Classifier Model

In [48]:
from sklearn.ensemble import BaggingClassifier
bagging= BaggingClassifier()
bagging.fit(x_train, y_train)

BaggingClassifier()

In [49]:
# Model Prediction
y_pred_train=bagging.predict(x_train)
y_pred_test=bagging.predict(x_test)

In [50]:
# Model evaluation
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [52]:
print(classification_report(y_train,y_pred_train))
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5975
           1       1.00      1.00      1.00      5969

    accuracy                           1.00     11944
   macro avg       1.00      1.00      1.00     11944
weighted avg       1.00      1.00      1.00     11944

              precision    recall  f1-score   support

           0       0.97      0.89      0.93      1988
           1       0.90      0.97      0.93      1994

    accuracy                           0.93      3982
   macro avg       0.93      0.93      0.93      3982
weighted avg       0.93      0.93      0.93      3982



In [53]:
print(confusion_matrix(y_train,y_pred_train))
print(confusion_matrix(y_test,y_pred_test))

[[5951   24]
 [  20 5949]]
[[1768  220]
 [  55 1939]]


In [54]:
print(accuracy_score(y_train,y_pred_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_test))

0.9963161419959813
######################################################################################################################################################
0.930939226519337


In [ ]:
# bagging:
# Training -99.67%
#test-93.67%

#Random Forest:
 #Training -1.0%
#test-94%

# Random Forest algorithm

In [55]:
from sklearn.ensemble import RandomForestClassifier
rforest=RandomForestClassifier()
rforest.fit(x_train,y_train)

RandomForestClassifier()

In [56]:
# Evaluation
y_pred_rf_train=rforest.predict(x_train)
y_pred_rf_test=rforest.predict(x_test)

In [60]:
print(classification_report(y_train,y_pred_rf_train))
print("#####"*30)
print(classification_report(y_test,y_pred_rf_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5975
           1       1.00      1.00      1.00      5969

    accuracy                           1.00     11944
   macro avg       1.00      1.00      1.00     11944
weighted avg       1.00      1.00      1.00     11944

######################################################################################################################################################
              precision    recall  f1-score   support

           0       0.98      0.91      0.94      1988
           1       0.91      0.98      0.95      1994

    accuracy                           0.95      3982
   macro avg       0.95      0.95      0.95      3982
weighted avg       0.95      0.95      0.95      3982



In [61]:
print(confusion_matrix(y_train,y_pred_rf_train))
print("#####"*30)
print(confusion_matrix(y_test,y_pred_rf_test))

[[5975    0]
 [   0 5969]]
######################################################################################################################################################
[[1802  186]
 [  32 1962]]


In [62]:
print(accuracy_score(y_train,y_pred_rf_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_rf_test)) 

1.0
######################################################################################################################################################
0.945253641386238


# Gradient Boosting Algorithm

In [63]:
from sklearn.ensemble import GradientBoostingClassifier
gdboost=GradientBoostingClassifier()
gdboost.fit(x_train,y_train)

GradientBoostingClassifier()

In [64]:
y_pred_gdboost_train=gdboost.predict(x_train)
y_pred_gdboost_test=gdboost.predict(x_test)

In [66]:
print(classification_report(y_train,y_pred_gdboost_train))
print("#####"*30)
print(classification_report(y_test,y_pred_gdboost_test))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81      5975
           1       0.82      0.79      0.81      5969

    accuracy                           0.81     11944
   macro avg       0.81      0.81      0.81     11944
weighted avg       0.81      0.81      0.81     11944

######################################################################################################################################################
              precision    recall  f1-score   support

           0       0.78      0.81      0.79      1988
           1       0.80      0.77      0.78      1994

    accuracy                           0.79      3982
   macro avg       0.79      0.79      0.79      3982
weighted avg       0.79      0.79      0.79      3982



In [67]:
print(classification_report(y_train,y_pred_gdboost_train))
print("#####"*30)
print(classification_report(y_test,y_pred_gdboost_test))

[[4971 1004]
 [1271 4698]]
######################################################################################################################################################
[[1601  387]
 [ 458 1536]]


In [68]:
print(accuracy_score(y_train,y_pred_gdboost_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_gdboost_test)) 

0.8095277963831212
######################################################################################################################################################
0.7877950778503264


# Adaboost Algorithm

In [69]:
from sklearn.ensemble import AdaBoostClassifier
ada= AdaBoostClassifier()
ada.fit(x_train,y_train)

AdaBoostClassifier()

In [70]:
y_pred_ada_train=ada.predict(x_train)
y_pred_ada_test=ada.predict(x_test)

In [71]:
print(classification_report(y_train,y_pred_ada_train))
print("#####"*30)
print(classification_report(y_test,y_pred_ada_test))

              precision    recall  f1-score   support

           0       0.77      0.80      0.79      5975
           1       0.79      0.76      0.78      5969

    accuracy                           0.78     11944
   macro avg       0.78      0.78      0.78     11944
weighted avg       0.78      0.78      0.78     11944

######################################################################################################################################################
              precision    recall  f1-score   support

           0       0.77      0.79      0.78      1988
           1       0.78      0.76      0.77      1994

    accuracy                           0.77      3982
   macro avg       0.77      0.77      0.77      3982
weighted avg       0.77      0.77      0.77      3982



In [72]:
print(accuracy_score(y_train,y_pred_ada_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_ada_test)) 

0.7828198258539852
######################################################################################################################################################
0.7742340532395781


In [74]:
print(accuracy_score(y_train,y_pred_ada_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_ada_test)) 

0.7828198258539852
######################################################################################################################################################
0.7742340532395781


In [ ]:
# bagging:
# Training -99.67%
#test-93.67%

#Random Forest:
 #Training -1.0%
#test-94%

#Gradient Boost Algorithm

# XGboost Algorithm

In [75]:
! pip install xgboost

     -------------------------------------- 125.4/125.4 MB 2.2 MB/s eta 0:00:00


In [76]:
from xgboost import XGBClassifier
xgb= XGBClassifier()
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [77]:
y_predict_xgb_train=xgb.predict(x_train)
y_predict_xgb_test=xgb.predict(x_test)

In [79]:
print(accuracy_score(y_train,y_predict_xgb_train))
print("#####"*30)
print(accuracy_score(y_test,y_predict_xgb_test)) 

0.9555425318151373
######################################################################################################################################################
0.8887493721747866


# Decision Tree Algorithm

In [80]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [81]:
y_pred_dt_train=dt.predict(x_train)
y_pred_dt_test=dt.predict(x_test)

In [83]:
print(accuracy_score(y_train,y_pred_dt_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_dt_test)) 

1.0
######################################################################################################################################################
0.9095931692616775


In [ ]:
# bagging:
# Training -99.67%
#test-93.67%

#Random Forest:
 #Training -100%
#test-94%

#Gradient Boost Algorithm
#train- 80.95%
#test- 78%

#Adaboost
#train- 77.73%
#test- 76.61%

#Xgboost
#Train-95%
#Test-89.2%

#DecisionTree
#Train-100%
#Test-91%

# Logistice Regression

In [84]:
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
logit.fit(x_train,y_train)

LogisticRegression()

In [85]:
y_pred_logit_train=logit.predict(x_train)
y_pred_logit_test=logit.predict(x_test)

In [86]:
print(accuracy_score(y_train,y_pred_logit_train))
print("#####"*30)
print(accuracy_score(y_test,y_pred_logit_test)) 

0.7061286001339585
######################################################################################################################################################
0.7041687594173782


In [ ]:
# bagging:
# Training -99.67%
#test-93.67%

#Random Forest:
 #Training -100%
#test-94%

#Gradient Boost Algorithm
#train- 80.95%
#test- 78%

#Adaboost
#train- 77.73%
#test- 76.61%

#Xgboost
#Train-95%
#Test-89.2%

#DecisionTree
#Train-100%
#Test-91%

#LogisticRegression
#train-70.7% 
#test-70.4%

In [ ]:
# Conclusion: RandomForest Is The Best Model As listed Above